version: "3.5"
services:
  jupyterlab:
    image: jupyter/tensorflow-notebook:latest
    container_name: jupyterlab
    ports:
      - "10000:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - TZ=Asia/Tokyo
    volumes:
      - .:/home/javyan/work
    command: sh /home/javyan/work/go.sh